### ISSUE TITLE
[BUG] docs typo

### ISSUE THREAD

**Issue by jimt** [gogrlx/grlx#114]
On https://docs.grlx.dev/architecture/overview/#farmer
> Additionally, the farmer contains is responsible for holding your [recipes]

Delete word `contains`

**Comment by jimt** [comment]
And on https://docs.grlx.dev/ingredients/overview/

> This also allows for users to develop [go plugins](https://pkg.go.dev/plugin) to extend ingredient providers.

The word `for` is unnecessary.

**Comment by jimt** [comment]
And on https://docs.grlx.dev/recipes/overview/ the **Note** says

> Otherwise, are steps run as is. If order is important, then requisites must be specified.

I am not sure of the author's intention, but I suspect `are` was meant to be `the`.

**Comment by taigrr** [comment]
Thanks!

**Comment by jimt** [comment]
Great.

The Note on https://docs.grlx.dev/recipes/overview/ still looks wrong.
