### ISSUE TITLE
[BUG] govulncheck is not assigning GO_VERSION correctly

### ISSUE THREAD

**Issue by ethanholz** [gogrlx/grlx#60]
**Please describe the issue.**
In the Github action, we are currently not setting the GO_VERSION variable correctly.

**Does this bug exist on the tip of master?**
[ X] Yes
[ ] No

**Comment by taigrr** [comment]
There's an [issue with codeQL](https://github.com/github/codeql/issues/13992).
I've submitted [this PR upstream](https://github.com/github/codeql/pull/14314) to codeql to see if we can get this addressed
