### ISSUE TITLE
[FEAT] Remove Viper

### ISSUE THREAD

**Issue by taigrr** [gogrlx/grlx#66]
Viper depends on hcl / hashicorp, which uses the MPL. As a result, we need to bundle the source code into `dependencies`, and it balloons to 1.5MB (all other deps only require LICENSE/NOTICE). We may desire to integrate HCL support later anyways, but we'd probably do it via a plugin to prevent shipping the HCL repo code in grlx.

Just a thought.

**Comment by ethanholz** [comment]
Agreed, HCL might not be what we want to use for configuration. At the start, YAML + JSON (and maybe TOML), would be a good start and would be easy enough to implement and maintain.

**Comment by taigrr** [comment]
We're not currently supporting HCL at all, but it's brought in as a dependency regardless.

If we were to support HCL in the future it would likely be as a plugin/module and more as a deploy integration.

We wouldn't want to allow users to use HCL as a recipe file format.
